name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@master
        with:
          java-version: '11'
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run tests in Firebase emulator
        uses: w9jds/firebase-action@master
        with:
          args: emulators:exec --only firestore 'npm test'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
