name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          java-version: '11'
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup firebase-tools
        run: npm install -g firebase-tools
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run tests in Firebase emulator
        run: firebase emulators:exec --only firestore 'npm test' --token '${{ secrets.FIREBASE_TOKEN }}'
